apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${{values.artifact_id}}.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ include "${{values.artifact_id}}.fullname" . }}"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-${{values.artifact_id}}"
    {{- include "${{values.artifact_id}}.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "${{values.artifact_id}}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "${{values.artifact_id}}.selectorLabels" . | nindent 8 }}
    spec:
      {{- if eq .Values.image.usePullSecret true }}
      imagePullSecrets:
      - name: {{ include "${{values.artifact_id}}.fullname" . }}-pull-secret
      {{- end }}
      {{ if eq .Values.useServiceAccount true }}
      serviceAccountName: {{ include "${{values.artifact_id}}.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /
            name: {{ include "${{values.artifact_id}}.fullname" . }}-config
            readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: config.txt
            path: config.txt
          name: {{ include "${{values.artifact_id}}.fullname" . }}-config
        name: {{ include "${{values.artifact_id}}.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
