{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ include "${{values.artifact_id}}.fullname" . }}"}]'
  labels:
    app: {{ include "${{values.artifact_id}}.fullname" . }}
    app.kubernetes.io/component: {{ include "${{values.artifact_id}}.fullname" . }}
    app.kubernetes.io/instance: {{ include "${{values.artifact_id}}.fullname" . }}
    app.kubernetes.io/name: {{ include "${{values.artifact_id}}.fullname" . }}
    app.kubernetes.io/part-of: "{{ .Release.Name }}-${{values.artifact_id}}"
  name: {{ include "${{values.artifact_id}}.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "${{values.artifact_id}}.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
{{- end }}
