apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-rest-ml
  title: AI/ML REST Python Service (v1.0)
  description: Python 3.11 web application ready for Data Science and AI/ML use cases.
  tags:
    - recommended
    - python
    - ai
    - llm
    - rest
spec:
  owner: user:default/glroland
  type: service

  parameters:
    - title: Describe the new business service
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Service Name
          type: string
          description: Unique name of the component (no spaces)
          ui:field: EntityNamePicker
        description:
          title: Description of the new business service and its purpose
          type: string
          description: Help others understand what this service is for and the business purpose it supports.
        owner:
          title: Developer Catalog Owner
          type: string
          description: Owner of the component in Red Hat Develper Hub
          ui:field: OwnerPicker
          default: glroland
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a GitHub location for the service
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: github.com
              enum:
                - github.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: glroland
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          artifact_id: ${{ parameters.component_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ parameters.owner }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.component_id }}
          http_port: 8080

    - id: publish
      name: Publish
      action: publish:github
      input:
        defaultBranch: main
        protectDefaultBranch: false
        description: This is ${{ parameters.component_id }}.  ${{ parameters.description }}
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public    # or 'internal' or 'private'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
      - title: Code in DevSpaces
        url: https://devspaces.apps.ocpprod.home.glroland.com/dashboard/#/load-factory?url=${{ steps.publish.output.remoteUrl }}
      - title: Developer Hub Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: OpenShift AI
        icon: chat
        url: https://rhods-dashboard-redhat-ods-applications.apps.ocpprod.home.glroland.com/projects
