---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notebook
spec:
  replicas: 1
  selector: {}
  serviceName: notebook
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: notebook
          image: registry.home.glroland.com/paas/notebook-3.11:latest
          imagePullPolicy: Always
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/opendatahub/jovyan
                --ServerApp.quit_button=False
                --ServerApp.tornado_settings={"user":"glroland","hub_host":"https://opendatahub.io","hub_prefix":"/notebookController/glroland"}
          ports:
            - name: notebook-port
              protocol: TCP
              containerPort: 8888
          livenessProbe:
            tcpSocket:
              port: notebook-port
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /notebook/opendatahub/glroland/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
