apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.artifact_id | dump}}
  description: "${{values.description}}"
  labels:
    app.kubernetes.io/name: ${{values.artifact_id}}-component
    app.kubernetes.io/part-of: ${{values.artifact_id}}-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"${{values.artifact_id}}-deploy"}]'
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: '${{values.artifact_id | dump}}'
    argocd/app-name: ${{values.artifact_id | dump}}
    argocd/instance-name: 'argoInstance'
    quay.io/repository-slug: '${{ values.repo.owner }}/${{values.artifact_id}}'
  links:
    - url: 'https://devspaces.apps.ocpprod.home.glroland.com/#https://github.com/${{values.destination.owner + "/" + values.destination.repo}}.git'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
  tags:
    - java
    - ai
    - agent
    - llm
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  definition:
    $text: ./openapi.yaml
