apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.artifact_id | dump}}
  description: '${{values.description}}'
  labels:
    app.kubernetes.io/name: ${{values.artifact_id}}-component
    app.kubernetes.io/part-of: ${{values.artifact_id}}-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"${{values.artifact_id}}-deploy"}]'
  tags:
    - python
    - ai
    - llm
    - rest
  links:
    - url: '${{ steps.publish.output.remoteUrl }}'
      title: 'GitHub Repository'
      icon: github
      type: git

    - url: 'https://devspaces.apps.ocpprod.home.glroland.com/dashboard/#/load-factory?url=${{ steps.publish.output.remoteUrl }}'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: aiml
