apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.artifact_id | dump}}
  description: "${{values.description}}"
  labels:
    app.kubernetes.io/name: ${{values.artifact_id}}-component
    app.kubernetes.io/part-of: ${{values.artifact_id}}-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"${{values.artifact_id}}-deploy"}]'
  tags:
    - python
    - ai
    - llm
    - rest
    - host_${{ values.repoUrl.host }}
    - project_${{ values.repoUrl.project }}
    - repo_${{ values.repoUrl.repo }}
    - remoteurl_${{ steps.createRepository.output.remoteUrl }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: aiml
