apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-rhdh-customization-provider
spec:
  destination:
    name: ''
    namespace: devhub
    server: 'https://kubernetes.default.svc'
  source:
    path: 'utils/ai-rhdh-customization-provider/helm'
    repoURL: 'https://github.com/glroland/ai-backstage-templates.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
