apiVersion: v1
kind: Service
metadata:
  name: {{ include "${{values.artifact_id}}.fullname" . }}
  labels:
    {{- include "${{values.artifact_id}}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  sessionAffinity: None
  selector:
    {{- include "${{values.artifact_id}}.selectorLabels" . | nindent 4 }}
